@startuml
class User{
    Username: String
    Password: String
    Email: String
    Administrator: Boolean
}

class University{
    Name: String
    Country: String
    City: String
}

class Degree{
    Name: String
    Faculty:String
}

class Subject{
    Name: String
    Course: BigDecimal
    Optional: Boolean
}

class Resources{
    Name: String
    Description: String
}

class Notes extends Resources{
    File: String
}

class Tests extends Resources{
    File: String
}

class Assignments extends Resources{
    File: String
}

class Rating{
    Rating: BigDecimal
    Comment: String
}


User "1" -- "*" Resources: Manages >
User "1" -- "*" Rating: Manages >
User "*" --left-- "*" University: Manages >
User "*" --left-- "*" Degree: Manages >
User "*" --left-- "*" Subject: Manages >
User "*" -- "*" Resources: Deletes >
User "*" -- "*" Rating: Deletes >
Rating "*" -- "1" Resources: Belongs >
Resources "*" -- "1-*" Subject: Belongs >
Subject "*" -- "*" Degree: Belongs >
Degree "*" -- "*" University: Belongs >
@enduml